"""Pattern analyzer: insights are generated by an LLM over the whole dataset,
not hardcoded — so they stay honest to the data. Counts are computed in code and
handed to the model so it can't invent numbers."""

from __future__ import annotations

import collections
import json

from llm import LLM
from models.result import ResearchRun
from prompts import PATTERN_SYSTEM, PATTERN_USER

EMIT_PATTERNS = {
    "name": "emit_patterns",
    "description": "Return the cross-cutting patterns as structured JSON.",
    "input_schema": {
        "type": "object", "additionalProperties": False,
        "required": ["headline", "insights", "easy_wins", "needs_outreach", "surprises"],
        "properties": {
            "headline": {"type": "string"},
            "insights": {"type": "array", "items": {
                "type": "object", "additionalProperties": False,
                "required": ["title", "detail", "evidence_count"],
                "properties": {"title": {"type": "string"}, "detail": {"type": "string"},
                               "evidence_count": {"type": "integer"}}}},
            "easy_wins": {"type": "array", "items": {"type": "string"}},
            "needs_outreach": {"type": "array", "items": {"type": "string"}},
            "surprises": {"type": "array", "items": {"type": "string"}},
        },
    },
}


def compute_counts(run: ResearchRun) -> dict:
    apps = run.apps
    def c(key):
        m = collections.Counter()
        for a in apps:
            v = a.val(key)
            (m.update(v) if isinstance(v, list) else m.update([v]))
        return dict(m.most_common())
    obtainable = {"self-serve", "sandbox-self-serve", "trial-only", "waitlist"}
    return {
        "n": len(apps),
        "auth": c("auth_methods"), "access": c("access"), "api_surface": c("api_surface"),
        "mcp": c("has_mcp"), "composio": c("composio_toolkit"), "buildability": c("buildability"),
        "self_serve": sum(1 for a in apps if a.val("access") in obtainable),
        "avg_score": round(sum(a.buildability_score for a in apps) / max(1, len(apps)), 1),
    }


class PatternAnalyzer:
    def __init__(self, model=None, provider=None, llm=None):
        import config
        self.model = model or config.PATTERN_MODEL
        self.llm = llm or LLM(self.model, provider)

    async def analyze(self, run: ResearchRun) -> dict:
        counts = compute_counts(run)
        rows = [{"id": a.id, "name": a.name, "category": a.category,
                 "auth": a.val("auth_methods"), "access": a.val("access"),
                 "api": a.val("api_surface"), "mcp": a.val("has_mcp"),
                 "composio": a.val("composio_toolkit"), "score": a.buildability_score}
                for a in run.apps]
        patterns = await self.llm.structured(
            system=PATTERN_SYSTEM,
            user=PATTERN_USER.format(counts=json.dumps(counts, ensure_ascii=False),
                                     rows=json.dumps(rows, ensure_ascii=False)),
            tool_name="emit_patterns", tool_desc=EMIT_PATTERNS["description"],
            schema=EMIT_PATTERNS["input_schema"], max_tokens=2500,
        )
        patterns["counts"] = counts
        return patterns
